- hosts: homelab
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
  roles:
    # - role: harden_linux
    #   tags: role-harden-linux
    - role: ansible_role_wireguard
      tags: role-wireguard