- hosts: homelab
  tasks:
    - ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: true
  roles:
    - role: ansible_role_wireguard
      tags: role-wireguard
