---
all:
  vars:
    ansible_user: root
    ansible_port: 22
  children:
    homelab:
      hosts:
        homelab-node1: &homelab-node1
          ansible_host: 192.168.1.50
        homelab-node2: &homelab-node2
          ansible_host: 192.168.1.51
        homelab-node3:
          ansible_host: 135.181.43.226
    kube_control_plane:
      hosts:
        homelab-node1: *homelab-node1
        homelab-node2: *homelab-node2
    etcd:
      hosts:
        homelab-node1: *homelab-node1

    kube_node:
      children:
        homelab:

    calico_rr:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
        calico_rr:
